### ISSUE TITLE
considered lwip?

### ISSUE THREAD

**Issue by dckc** [sgielen/cosix#4]
RELEASE-1.0.md notes issues with the TCP/IP implementation here. My impression is that [lwip](http://savannah.nongnu.org/projects/lwip/) is pretty complete and mature. (I think I discovered it via genode). Care to share your motivation for a from-scratch TCP/IP implementation?

**Comment by dckc** [comment]
p.s. I'm also interested in any thoughts on how cosix relates to genode and seL4.

**Comment by sgielen** [comment]
I didn't know about lwip, but that seems very useful! I don't have a very good motivation for writing a TCP/IP implementation from scratch, other than that I didn't expect there to be an existing userland stack I could fit into the design of CloudABI.

Thanks for letting me know about this, it would be really useful if this could be ported and used instead of the current networkd.

I don't really know about the relation with genode and seL4, but I'll check that out as well!

**Comment by dckc** [comment]
I think my goal of bringing it to your attention is achieved. Thanks.
